service: authorization-service
frameworkVersion: '2'

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-1

  environment:
    TEST_USER: ${env:TEST_USER}

plugins:
  - serverless-webpack

functions:
  basicAuthorizer:
    handler: handler.basicAuthorizer
