service: import-service
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: "s3:*"
          Resource: "arn:aws:s3:::shop-import-service-bucket/*"

plugins:
  - serverless-webpack

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true
