service: import-service
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-1

plugins:
  - serverless-webpack

functions:
  importProductsFile:
    handler: handler.importProductsFile
