service: import-service
frameworkVersion: '2'

useDotenv: true

provider:
  name: aws
  runtime: nodejs12.x
  lambdaHashingVersion: 20201221
  region: eu-west-1
  iam:
    role:
      statements:
        - Effect: "Allow"
          Action: "s3:*"
          Resource: "arn:aws:s3:::shop-import-service-bucket/*"
        - Effect: Allow
          Action: "sqs:*"
          Resource:
            - Fn::GetAtt:
              - catalogItemsQueue
              - Arn

  environment:
    PG_HOST: ${env:PG_HOST}
    PG_PORT: ${env:PG_PORT}
    PG_DBNAME: ${env:PG_DBNAME}
    PG_USERNAME: ${env:PG_USERNAME}
    PG_PASSWORD: ${env:PG_PASSWORD}
    SQS_URL: ${env:SQS_URL}

plugins:
  - serverless-webpack

resources:
  Resources:
    catalogItemsQueue:
      Type: "AWS::SQS::Queue"
      Properties:
        QueueName: "catalogItemsQueue"

functions:
  importProductsFile:
    handler: handler.importProductsFile
    events:
      - http:
          path: import
          method: get
          cors: true
          request:
            parameters:
              querystrings:
                name: true

  importFileParser:
    handler: handler.importFileParser
    events:
      - s3:
          bucket: shop-import-service-bucket
          existing: true
          event: s3:ObjectCreated:*
          rules:
            - prefix: uploaded/
            - suffix: .csv

  catalogBatchProcess:
    handler: handler.catalogBatchProcess
    events:
      - sqs:
          batchSize: 5
          arn:
            Fn::GetAtt:
              - catalogItemsQueue
              - Arn
